theme: jekyll-theme-hacker
title: Daniel page
description: Bookmark this to keep an eye on my project updates!
#google_analytics: G-E9PS39NY6J
email: danielprisco09@gmail.com 
twitter_username: blikor_sqwt 
github_username: dlprisco 
linkedin_username: daniel-prisco-4b3965274
author: Daniel Prisco
